name: Sphinx build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sphinx to GitHub Pages
      uses: sphinx-notes/pages@1.0
      with:
        documentation_path: docs/source
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
